# Generated by Django 4.0.6 on 2022-07-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuntact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
