# Generated by Django 4.0.6 on 2022-07-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
    ]
