# Generated by Django 4.0.6 on 2022-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sl',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
