# Generated by Django 4.0.6 on 2022-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sl',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
