# Generated by Django 4.0.6 on 2022-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sl',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
