# Generated by Django 4.0.6 on 2022-07-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_post_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='articl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='Blog.post'),
        ),
    ]
